export const ForecastData = [
    {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/2/2019",
        "Forecast": 22,
        "Actual": 22
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/9/2019",
        "Forecast": 23,
        "Actual": 24
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/16/2019",
        "Forecast": 26,
        "Actual": 26
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/23/2019",
        "Forecast": 29,
        "Actual": 28
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/30/2019",
        "Forecast": 32,
        "Actual": 30
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "12/7/2019",
        "Forecast": 35,
        "Actual": 32
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "12/14/2019",
        "Forecast": 38,
        "Actual": 34
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "12/21/2019",
        "Forecast": 41,
        "Actual": 36
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "12/28/2019",
        "Forecast": 44,
        "Actual": 38
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "1/4/2020",
        "Forecast": 47,
        "Actual": 40
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "1/11/2020",
        "Forecast": 50,
        "Actual": 42
      },
      {
        "SKU": 10203,
        "Product": "Choclate Truffle Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "1/18/2020",
        "Forecast": 53,
        "Actual": 44
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/2/2019",
        "Forecast": 20,
        "Actual": 22
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/9/2019",
        "Forecast": 23,
        "Actual": 24
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/16/2019",
        "Forecast": 26,
        "Actual": 26
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/23/2019",
        "Forecast": 29,
        "Actual": 28
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "11/30/2019",
        "Forecast": 32,
        "Actual": 30
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "12/7/2019",
        "Forecast": 35,
        "Actual": 32
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "12/14/2019",
        "Forecast": 38,
        "Actual": 34
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "12/21/2019",
        "Forecast": 41,
        "Actual": 36
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "12/28/2019",
        "Forecast": 44,
        "Actual": 38
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "1/4/2020",
        "Forecast": 47,
        "Actual": 40
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "1/11/2020",
        "Forecast": 50,
        "Actual": 42
      },
      {
        "SKU": 10201,
        "Product": "Choclate Cake",
        "Segment": "Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 1,
        "Date": "1/18/2020",
        "Forecast": 53,
        "Actual": 44
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "11/2/2019",
        "Forecast": 20,
        "Actual": 22
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "11/9/2019",
        "Forecast": 23,
        "Actual": 24
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "11/16/2019",
        "Forecast": 26,
        "Actual": 26
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "11/23/2019",
        "Forecast": 29,
        "Actual": 28
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "11/30/2019",
        "Forecast": 32,
        "Actual": 30
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "12/7/2019",
        "Forecast": 35,
        "Actual": 32
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "12/14/2019",
        "Forecast": 38,
        "Actual": 34
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "12/21/2019",
        "Forecast": 41,
        "Actual": 36
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "12/28/2019",
        "Forecast": 44,
        "Actual": 38
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "1/4/2020",
        "Forecast": 47,
        "Actual": 40
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "1/11/2020",
        "Forecast": 50,
        "Actual": 42
      },
      {
        "SKU": 10202,
        "Product": "Vanilla Cake",
        "Segment": "Cup Cake",
        "Size": "S06",
        "Category": "LTO",
        "PackageSize": 1,
        "Conversion": 0.05,
        "Date": "1/18/2020",
        "Forecast": 53,
        "Actual": 44
      }
    ]